name: 'Create Github Issue'

description: 'Create new Github Issue'

inputs:
  github-token:
    description: 'Github token'
    required: true
  issue-title:
    description: 'Title of the issue'
    required: true
  issue-body:
    description: 'Body of the issue'
    required: true

outputs:
  issue-number:
    description: 'The number of the created issue'
  issue-url:
    description: 'The URL of the created issue'

runs:
  using: 'node16'
  main: 'index.js'
